image: Visual Studio 2015
version: 0.0.1.{build}

branches:
  only:
    - master
    - /package\/.*/

environment:
  MYGET_FEED: 'https://www.myget.org/F/kai2nenobu'
  MYGET_API_KEY:
    secure: Y/8UFTPxim7reHigg7iClTv5cu1QI4yA+zPs4DelBkFyMlUZxkzppJGkijKUuRVZ
  MINGW_ROOT: 'C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32'
  MSYS2_ROOT: 'C:\msys64'
# Disable automatic builds
build: off
before_build:
  - dir "%MINGW_ROOT%"
  - dir "%MINGW_ROOT%\bin"
  - dir "%MSYS2_ROOT%\usr\bin"
  - dir "%MSYS2_ROOT%\mingw32\bin"
  # Detect a target package from a tag name or a branch name
  - ps: |
      if ($env:APPVEYOR_REPO_BRANCH -eq 'master')  {
        if ($env:APPVEYOR_REPO_TAG_NAME) {
          $array = $env:APPVEYOR_REPO_TAG_NAME -split '/'
          $env:PACKAGE_ID = $array[0]
          $env:PACKAGE_VERSION = $array[1]
        } else {
          Write-Error -Message "Build on master branch must have a tag"
          exit 1
        }
      } else {
        $array = $env:APPVEYOR_REPO_BRANCH -split '/'
        $env:PREFIX = $array[0]
        $env:PACKAGE_ID = $array[1]
      }
build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%\%PACKAGE_ID%"
  # Build
  - if exist build.bat .\build.bat
  # Packaging
  - choco pack
  - dir
test_script:
  - cd "%APPVEYOR_BUILD_FOLDER%\%PACKAGE_ID%"
  - if exist test.bat .\test.bat
deploy_script:
  - cd "%APPVEYOR_BUILD_FOLDER%\%PACKAGE_ID%"
  - choco push -s "%MYGET_FEED%" -k "%MYGET_API_KEY%"
artifacts:
  # pushing all *.nupkg files in build directory recursively
  - path: '**\*.nupkg'
notifications:
  - provider: Slack
    incoming_webhook:
      secure: Xy6BVJYVnM0lJ0eD9Uw8z1XSEFErqUbRozlhX7gmoAWDUJ2VfDgH3JId4mAOkz3vZ6wlQenfCc2Lyotvf0ABfZygpjB0qYD++2Pl/HsRLPw=
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: false
